Repository civictechro/fiipregatit.ro, pull requests merged in 2018-02, with the labels that each got.

#129 fix(guides) Proper page counter
  site/web/app/lib/Entity/Guide.php
  site/web/app/themes/sage/templates/content-single-ghid.php
  site/web/app/themes/sage/templates/mustache/guide.mustache
Labels: in progress

#130 feat(personal_plan) Add personal plan page
  site/web/app/lib/App.php
  site/web/app/lib/CustomPage/BaseCustomPage.php
  site/web/app/lib/CustomPage/PersonalPlanPage.php
  site/web/app/lib/CustomPageManager.php
  site/web/app/lib/Entity/Entity.php
  site/web/app/lib/Entity/PersonalPlan.php
  site/web/app/lib/Repository/AbstractRepository.php
  site/web/app/themes/sage/assets/images/plan_pers_ghid.png
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/templates/content-plan-personal.php
  site/web/app/themes/sage/templates/head.php
  site/web/app/themes/sage/templates/mustache/guide.mustache
  site/web/app/themes/sage/templates/mustache/plan_personal.mustache
Labels: in progress

#131 fix(scaffolding) Export plan field group
  site/config/misc/acf-export-2018-02-10.json
  site/config/misc/plan-personal-acf-export-2018-02-10.json
Labels: in progress

#132 fix(cleanup) We're not using this image anymore
  site/web/app/themes/sage/images/logo.png
Labels: in progress

#133 fix(guides) Fix list style (overflow)
  site/web/app/themes/sage/assets/styles/common/_global.scss
Labels: in progress

#134 fix(guides) Show related guides instead of randomly picking two
  site/web/app/lib/Entity/Guide.php
  site/web/app/lib/Repository/AbstractRepository.php
  site/web/app/lib/Repository/GuideRepository.php
  site/web/app/themes/sage/templates/content-single-ghid.php
Labels: in progress

#135 fix(guides) Don't use event name in card headers on guide page
  site/web/app/themes/sage/templates/mustache/guide.mustache
Labels: in progress

#136 fix(guide) Center recommandations on guide detail page
  site/web/app/themes/sage/templates/content-single-ghid.php
  site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Labels: in progress

#137 feat(gallery) Add gallery to guides via CMB
  site/composer.json
  site/composer.lock
  site/web/app/lib/App.php
  site/web/app/lib/Entity/Guide.php
  site/web/app/lib/Repository/GuideRepository.php
  site/web/app/mu-plugins/fiipregatit-content.php
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/templates/content-single-ghid.php
  site/web/app/themes/sage/templates/mustache/guide.mustache
Labels: in progress

#138 fix(gallery) Don't show extra info container when no extra info available
  site/web/app/themes/sage/templates/content-single-ghid.php
Labels: in progress

#139 fix(gallery) Show overall gallery photo count on homepage
  site/web/app/lib/Repository/GuideRepository.php
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/home.php
  site/web/app/themes/sage/templates/content-single-ghid.php
Labels: in progress

#140 fix(config) New field config, without guide gallery and campaign attachments
  site/config/misc/acf-export-2018-02-10-2.json
Labels: in progress

#141 fix(campaign) Use suggested guides on campaign detail page
  site/web/app/lib/Entity/Campaign.php
  site/web/app/lib/Repository/CampaignRepository.php
  site/web/app/themes/sage/templates/content-single-campanie.php
Labels: in progress

#142 fix(contact) Display contact cols on top of each other on small screens
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/templates/mustache/contact.mustache
Labels: in progress

#173 chore(readme) Add common error for Windows users to README
  README.md
Labels: in progress

#174 fix(campaign) Show image and text on top of each other on mobile
  site/web/app/themes/sage/templates/mustache/campaign.mustache
Labels: in progress

#175 fix(guide) By default, all accordion options are closed
  site/web/app/themes/sage/templates/mustache/guide.mustache
Labels: in progress

#176 fix(mobile) Hide social icons from the nav on mobile
  site/web/app/themes/sage/templates/header.php
Labels: in progress

#177 fix(mobile) Keep hamburger menu on the right side even on tiny screens
  site/web/app/themes/sage/assets/styles/layouts/_header.scss
Labels: in progress

#178 fix(guide) Add search header on guide listing page
  site/web/app/themes/sage/templates/listing-ghiduri.php
Labels: in progress

#179 fix(guide) Higher bottom padding on guides section
  site/web/app/themes/sage/assets/styles/common/_global.scss
Labels: in progress

#180 fix(footer) Small bottom padding
  site/web/app/themes/sage/assets/styles/layouts/_footer.scss
Labels: in progress

#182 fix(footer) Higher padding on top
  site/web/app/themes/sage/assets/styles/layouts/_footer.scss
Labels: in progress

#183 fix(campaigns) Show see all button on campaign section
  site/web/app/lib/App.php
  site/web/app/themes/sage/home.php
Labels: in progress

#184 fix(counter) Larger font size on count, homepage
  site/web/app/themes/sage/assets/styles/common/_global.scss
Labels: in progress

#185 fix(search) Smaller border on search box
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/assets/styles/components/_forms.scss
Labels: in progress

#186 fix(search) Make search box larger, match design
  site/web/app/themes/sage/assets/styles/components/_forms.scss
Labels: in progress

#187 fix(nav) Larger margin between items
  site/web/app/themes/sage/assets/styles/layouts/_header.scss
Labels: in progress

#188 fix(search) Center icon on search button
  site/web/app/themes/sage/assets/styles/components/_forms.scss
Labels: in progress

#189 fix(guide) Arrows down when closed, arrows up when open
  site/web/app/themes/sage/assets/styles/common/_global.scss
Labels: in progress

#190 fix(plan) Arrows down when closed, up when open
  site/web/app/themes/sage/assets/styles/common/_global.scss
Labels: in progress

#191 fix(campaign) Arrows down when closed, up when open
  site/web/app/themes/sage/assets/styles/common/_global.scss
Labels: in progress

#192 fix(guide) Allow all sections to be opened at the same time
  site/web/app/themes/sage/templates/mustache/guide.mustache
Labels: in progress

#193 fix(personal_plan) Don't show images on mobile
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/templates/mustache/plan_personal.mustache
Labels: in progress

#194 fix(personal_plan) Add one more section to the list
  site/config/misc/acf-export-2018-02-13.json
  site/web/app/lib/CustomPage/PersonalPlanPage.php
  site/web/app/lib/Entity/PersonalPlan.php
  site/web/app/themes/sage/templates/content-plan-personal.php
Labels: in progress

#195 fix(mobile) No glitch when opening the menu
  site/web/app/themes/sage/assets/styles/layouts/_header.scss
Labels: in progress

#196 fix(mobile) Fixed glitch also for larger devices
  site/web/app/themes/sage/assets/styles/layouts/_header.scss
Labels: in progress

#197 chore(export) Export prod. state (extra field on personal plan)
  site/config/misc/fiipregtitro.wordpress.2018-02-13.xml
Labels: in progress

#199 fix(homepage) Vertically center align photos -> text
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/home.php
  site/web/app/themes/sage/templates/mustache/app_promo.mustache
Labels: in progress

#200 fix(404) Translate error message
  site/web/app/themes/sage/404.php
Labels: in progress

#201 feat(dash) Generate dashboard guides from `.md` files
  site/web/app/themes/sage/composer.json
  site/web/app/themes/sage/composer.lock
  site/web/app/themes/sage/functions.php
  site/web/app/themes/sage/lib/DashboardGuides.php
  site/web/app/themes/sage/templates/markdown/Adaugă ghid.md
  site/web/app/themes/sage/templates/markdown/Contact CivicTech România.md
Labels: in progress

#202 Fixed Menu glitch expanding #198
  site/web/app/themes/sage/assets/styles/layouts/_header.scss
Labels: in progress

#203 fix(dash) Make images max 100% wide in dashboard
  site/web/app/themes/sage/lib/DashboardGuides.php
  site/web/app/themes/sage/templates/markdown/Adaugă ghid.md
Labels: in progress

#204 fix(contact) Better contact form with Pirate Forms
  site/composer.json
  site/composer.lock
  site/web/app/themes/sage/templates/contact.php
  site/web/app/themes/sage/templates/mustache/contact.mustache
Labels: in progress

#206 fix(contact) Better contact forms style (match theme)
  site/web/app/themes/sage/assets/styles/common/_global.scss
Labels: in progress

#207 Step1 - responsive font size for different elements.
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Labels: in progress

#210 fix(accesibility) Add accesibility plugin and translations
  site/composer.json
  site/composer.lock
  site/web/app/languages/admin-network-ro_RO.mo
  site/web/app/languages/admin-network-ro_RO.po
  site/web/app/languages/admin-ro_RO.mo
  site/web/app/languages/admin-ro_RO.po
  site/web/app/languages/continents-cities-ro_RO.mo
  site/web/app/languages/continents-cities-ro_RO.po
  site/web/app/languages/ro_RO.mo
  site/web/app/languages/ro_RO.po
Labels: in progress

#211 fix(header) Update tagline
  site/web/app/themes/sage/templates/header.php
Labels: in progress

#212 fix(plugin) New Pirate Forms plugin patch
  site/composer.json
  site/composer.lock
Labels: in progress

#216 fix(homepage) Add links to buttons on homepage
  site/web/app/themes/sage/home.php
  site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
  site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Labels: bug, in progress

#217 feat(campaign) Redesign campaign page layout
  site/web/app/lib/Entity/Guide.php
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/bower.json
  site/web/app/themes/sage/templates/content-single-campanie.php
  site/web/app/themes/sage/templates/footer.php
  site/web/app/themes/sage/templates/mustache/campaign.mustache
Labels: enhancement, in progress

#218 chore(export) Website content (22 feb)
  site/config/misc/fiipregtitro.wordpress.2018-02-22.xml
Labels: in progress

#219 feat(campaign) Allow attaching videos to campaigns
  site/web/app/lib/App.php
  site/web/app/lib/Entity/Campaign.php
  site/web/app/lib/Repository/CampaignRepository.php
  site/web/app/mu-plugins/fiipregatit-content.php
  site/web/app/themes/sage/templates/content-single-campanie.php
  site/web/app/themes/sage/templates/mustache/campaign.mustache
Labels: enhancement, in progress

#220 fix(guides) s/ghiduri educative/ghiduri
  site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Labels: in progress

#221 feat(first_aid) Add First Aid page
  site/config/misc/prim-ajutor-2-acf-export-2018-02-22.json
  site/config/misc/prim-ajutor-acf-export-2018-02-22.json
  site/web/app/lib/App.php
  site/web/app/lib/CustomPage/BaseCustomPage.php
  site/web/app/lib/CustomPage/FirstAidPage.php
  site/web/app/lib/CustomPageManager.php
  site/web/app/lib/Entity/FirstAid.php
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/home.php
  site/web/app/themes/sage/templates/content-prim-ajutor.php
  site/web/app/themes/sage/templates/mustache/first_aid.mustache
  site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Labels: enhancement, in progress

#222 chore(export) Staging export (2/22/2018)
  site/config/misc/staging-export-acf-export-2018-02-22.json
  site/config/misc/staging-export-fiipregtitro.wordpress.2018-02-22.xml
Labels: in progress

#223 fix(homepage) 8 guides on homepage, including first aid
  site/web/app/lib/App.php
Labels: in progress

#225 fix(header) Update copy and make more responsive
  site/web/app/themes/sage/assets/styles/layouts/_header.scss
  site/web/app/themes/sage/templates/header.php
Labels: in progress

#224 fix(homepage) Show four campaigns on md screens
  site/web/app/lib/App.php
  site/web/app/themes/sage/home.php
  site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
Labels: in progress

#226 fix(footer) New footer layout
  site/web/app/themes/sage/assets/images/Stema_IGSU_color.png
  site/web/app/themes/sage/assets/images/civictech_logo.svg
  site/web/app/themes/sage/assets/styles/layouts/_footer.scss
  site/web/app/themes/sage/templates/footer.php
Labels: in progress

#227 fix(home) Show 4 campaigns only on md screens
  site/web/app/themes/sage/home.php
  site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
Labels: in progress

#228 fix(campaign) Link title, photo
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/assets/styles/layouts/_footer.scss
  site/web/app/themes/sage/templates/mustache/campaign_listing.mustache
Labels: in progress

#229 fix(campaigns) Add search header on campaign listing page
  site/web/app/themes/sage/templates/listing-campanii.php
Labels: in progress

#230 fix(campaigns) Show only 3 campaigns on personal plan page
  site/web/app/themes/sage/templates/content-plan-personal.php
Labels: in progress

#231 fix(personal_plan) Collapse all items by default
  site/web/app/themes/sage/templates/content-plan-personal.php
Labels: in progress

#232 fix(guides) Include First Aid in the listing
  site/web/app/themes/sage/templates/listing-ghiduri.php
Labels: in progress

#233 fix(guide) Add First Aid link in sidebar
  site/web/app/themes/sage/templates/content-single-ghid.php
Labels: in progress

#234 fix(guide) Don't show link to same guide in sidebar
  site/web/app/themes/sage/templates/content-single-ghid.php
Labels: in progress

#235 fix(campaign) Smoother transition between screen sizes for campaigns
  site/web/app/themes/sage/templates/mustache/campaign.mustache
Labels: in progress

#236 fix(campaign) Always show close button on lightbox
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/templates/footer.php
  site/web/app/themes/sage/templates/mustache/campaign.mustache
Labels: in progress

#237 fix(404) "Four, oh four" custom template
  site/web/app/themes/sage/404.php
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/templates/mustache/404.mustache
Labels: in progress

#277 feat(about) Move about page to admin
  site/config/misc/about-page-acf-export-2018-02-25.json
  site/web/app/lib/App.php
  site/web/app/lib/CustomPage/AboutPage.php
  site/web/app/lib/CustomPageManager.php
  site/web/app/lib/Entity/About.php
  site/web/app/themes/sage/assets/styles/common/_global.scss
  site/web/app/themes/sage/templates/despre.php
  site/web/app/themes/sage/templates/mustache/despre.mustache
  site/web/app/themes/sage/templates/mustache/partials/despre_fii_pregatit.mustache
  site/web/app/themes/sage/templates/mustache/partials/faq.mustache
  site/web/app/themes/sage/templates/mustache/partials/press.mustache
  site/web/app/themes/sage/templates/mustache/partials/social_media.mustache
Labels: bug, enhancement

#282 fix(guides) Hover state update
  site/web/app/themes/sage/assets/styles/common/_global.scss
Labels: enhancement

#287 fix(guide) Don't widen button on small screens
  site/web/app/themes/sage/templates/mustache/guide_listing.mustache
Labels: bug

#298 fix(header) Add homepage link
  site/web/app/themes/sage/assets/styles/layouts/_header.scss
  site/web/app/themes/sage/functions.php
Labels: User Testing / 23-02-2018, enhancement

#316 fix(guide) Limit maximum guide icon size
  site/web/app/themes/sage/assets/styles/common/_global.scss
Labels: bug
